### ISSUE TITLE
CoordToWktOperation

### ISSUE THREAD

**Issue by mikegb92121** [giTorto/geoXtension#1]
Coordinate pattern does not take into account western or southern hemispheres (or eastern/northern if there is a + before the number).  I added [-+]? to the pattern and it now works with my data.

**Comment by giTorto** [comment]
Thank you very much... ;) 
Given that in WKT, positive numbers are written without '+' I decided to remove simply the '+' from the string. So, if a number is written like "+32.33", it becomes "32.33" in the point. In addition, I modified the pattern adding '[-]?' as requested. I hope this solves the issue.
